global_costmap:

  update_frequency: 0.5
  publish_frequency: 0.5

  # static_map: true
  rolling_window: false
  
  robot_radius: 0.04 # footprint
  
  plugins: 
   - {name: static_layer, type: "costmap_2d::StaticLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  static_layer:
    enabled: true
    map_topic: global_map
  
  inflation_layer:
    enabled: true
    inflation_radius: 0.14
    cost_scaling_factor: 10

