local_costmap:

  update_frequency: 1
  publish_frequency: 0.5
  
  rolling_window: true
  width: 14
  height: 12
  resolution: 0.06
  
  #footprint: [[0, 0.527], [1.582, 0.527], [1.582, -0.527], [0, -0.527]] # full robot footprint
  footprint: [[0, 0.427], [1.582, 0.427], [1.582, -0.427], [0, -0.427]] # reduced robot footprint

  plugins: 
   - {name: static_layer, type: "costmap_2d::StaticLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
  static_layer:
    enabled: true
    map_topic: global_map
  
  inflation_layer:
    enabled: true
    inflation_radius: 0.14
    cost_scaling_factor: 10
    