TebLocalPlannerROS:

  odom_topic: odom
     
  # Trajectory
   
  teb_autosize: true
  dt_ref: 0.45 # 0.3
  dt_hysteresis: 0.1
  min_samples: 4
  max_samples: 100
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: true
  max_global_plan_lookahead_dist: 7
  global_plan_viapoint_sep: -1
  global_plan_prune_distance: 1
  exact_arc_length: false
  feasibility_check_no_poses: 4
  publish_feedback: false
     
  # Robot
          
  max_vel_x: 0.8 # 0.6
  max_vel_x_backwards: 0.4
  max_vel_y: 0.0
  max_vel_theta: 0.3 # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
  acc_lim_x: 0.08 # 0.1
  acc_lim_theta: 0.1
  
  # ********************** Carlike robot parameters ********************
  min_turning_radius: 2.5 # 2.55    # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase: 1.582 # 1.6            # Wheelbase of our robot
  cmd_angle_instead_rotvel: true    # stage simulator takes the angle instead of the rotvel as input (twist message)
  # ********************************************************************
  
  footprint_model:
    type: "two_circles"
    front_offset: 1.5
    front_radius: 0.4
    rear_offset: 0.0
    rear_radius: 0.45
    #type: "line"
    #line_start: [0.0, 0.0] # for type "line"
    #line_end: [1.582, 0.0] # for type "line"
  
  # GoalTolerance
     
  xy_goal_tolerance: 0.25
  yaw_goal_tolerance: 0.15
  free_goal_vel: true
  complete_global_plan: false
     
  # Obstacles
     
  min_obstacle_dist: 0.1
  inflation_dist: 0.2
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 10
  legacy_obstacle_association: false
  obstacle_poses_affected: 15 # cantidad de teb poses tenidos en cuenta por cada obstáculo 
                              # (si legacy_obstacle_association=true)
  obstacle_association_force_inclusion_factor: 20 # todos los obstáculos dentro de este factor por el min_obstacle_dist son tenidos en cuenta 
                                                 # (solo importa si legacy_obstacle_association=false)
  obstacle_association_cutoff_factor: 40 # factor de min_obstacle_dist límite para tener en cuenta los obstáculos
  
  include_dynamic_obstacles: false 
  dynamic_obstacle_inflation_dist: 0.6 # include_dynamic_obstacles=true
  
  costmap_converter_plugin: "" # deshabilitado
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5
  
  # Optimization
  
  no_outer_iterations: 8 # 3
  no_inner_iterations: 4 # 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.06 # 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 100 # 1000
  weight_kinematics_forward_drive: 1 # 10
  weight_kinematics_turning_radius: 1.5 # 1.5
  weight_optimaltime: 1 # 1.5
  weight_shortest_path: 0
  weight_obstacle: 1 # 50
  weight_inflation: 1 # 0.1
  # weight_dynamic_obstacle: 10 # not in use yet
  # weight_dynamic_obstacle_inflation: 0.2
  # weight_viapoint: 1
  weight_adapt_factor: 1.1
  
  # Homotopy Class Planner
  
  enable_homotopy_class_planning: false
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.95
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: True
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False
  
  # Recovery
  
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
  